### ISSUE TITLE
Script doesn't work but its giving me nowhere to look for

### ISSUE THREAD

**Issue by joeydc** [josteink/le-godaddy-dns#15]
I'm running this script inside a brand new LXC container if that make any difference.
The cmds if done:
`sudo apt-get install python3 python3-pip curl`
`git clone https://github.com/lukas2511/dehydrated`
`git clone https://github.com/josteink/le-godaddy-dns`
`cd $HOME/le-godaddy-dns`
`python3 -m pip install -r requirements.txt --user`
```
Requirement already satisfied: certifi==2017.7.27.1 in /home/joeydc/.local/lib/python3.5/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: chardet==3.0.4 in /home/joeydc/.local/lib/python3.5/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: GoDaddyPy==2.2.5 in /home/joeydc/.local/lib/python3.5/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: idna==2.6 in /home/joeydc/.local/lib/python3.5/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: requests==2.18.4 in /home/joeydc/.local/lib/python3.5/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: urllib3==1.22 in /home/joeydc/.local/lib/python3.5/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: tld==0.7.9 in /home/joeydc/.local/lib/python3.5/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied: six>=1.9 in /home/joeydc/.local/lib/python3.5/site-packages (from tld==0.7.9->-r requirements.txt (line 7))
```
```
$ cat $HOME/dehydrated/domains.txt
hass.joey.****.ca
```
```
$ cat $HOME/dehydrated/config
HOOK_CHAIN="yes"
```
`export GD_KEY=*****`
`export GD_SECRET=*****`

**Here's all its giving me after running the script:**
```
joeydc@letsencrypt:~/dehydrated$ ./dehydrated --challenge dns-01 -k $HOME/le-godaddy-dns/godaddy.py -c
# INFO: Using main config file /home/joeydc/dehydrated/config
 + Godaddy hook executing: ***********************
Traceback (most recent call last):
  File "/home/joeydc/le-godaddy-dns/godaddy.py", line 119, in <module>
    main(sys.argv[1:])
  File "/home/joeydc/le-godaddy-dns/godaddy.py", line 115, in main
    ops[argv[0]](argv[1:])
KeyError: '**********************'
```

Can you help me out with this please? Am i missing something here?

**Comment by josteink** [comment]
Strange. 

From what I can tell, it seems `dehydrated` is invoking `le-godday-dns` using your API key (or secret
? better edit that post!) as the command-name.

I have no idea what would cause that, but it sounds like an error in dehydrated and how it invokes its DNS-hooks.

For reference, things seems to work for me, but I'm running an old revision of `dehydrated`, specifically I'm at hash `742c0ad176f173118d8d4b19d19cec962741f99b`.

If that works for you, I'd suggest filing a bug/issue with dehydrated, since this is clearly an error on their end, and how they invoke this hook.

**Comment by joeydc** [comment]
Thank you for your respond.
Using the old version of dehydrated fixed my issue. 
Hash `742c0ad176f173118d8d4b19d19cec962741f99b`

Thanks again !!

**Comment by josteink** [comment]
Sounds good. I recommend creating an issue upstream with dehydrated to ensure this gets fixed :)

**Comment by lukas2511** [comment]
This is not a dehydrated issue. Your script should ignore unknown hooks since new ones will be added from time to time. The "key" in this original issue was just a random generated string to cause broken hook-scripts to crash early, I now appended a human readable string to that to make it very clear what's going on.

**Comment by josteink** [comment]
Thanks for the heads up @lukas2511. I'll get it done.

**Comment by josteink** [comment]
@joeydc Latest version of `le-godday-dns` (as of https://github.com/josteink/le-godaddy-dns/commit/14f2a7a42c7c691b47d0a2093ae07e53c5ed79a7) should now support the `hook-bricker`, and thus the latest version of dehydrated.

So no need to stay on older versions.

**Comment by joeydc** [comment]
That's great, thank you for your time !

**Comment by lukas2511** [comment]
@josteink please don't check for the bricker hook... just ignore unknown hooks. there will be new hooks from time to time and people always come back to my repo "there is a new warning", "there is an error", please just silently ignore the new ones.

**Comment by josteink** [comment]
Ive explicitly added code to tell people to report issues here though. Isn’t that OK?

**Comment by lukas2511** [comment]
@josteink I'd prefer hook scripts to just silently ignore it, especially because the hook-bricker was originally designed to be just completely random, i just added added the human-readable part because people reported gibberish errors and I just removed the random part because i thought it was the reason some peoples scripts broke (due to incompatible openssl versions). Also if you only add noops for new hooks anyway it's probably easier for you to just ignore them to begin with.

**Comment by josteink** [comment]
Since you insist: https://github.com/josteink/le-godaddy-dns/commit/9d47f4e4c7d9f65c453db3c56ca2d25d3f333fb5

Considering this issue completely closed for now :)
