### ISSUE TITLE
Wildcard certificate issues

### ISSUE THREAD

**Issue by vogelfreiheit** [josteink/le-godaddy-dns#18]
Just observed this:

```
Processing *.devops.blahblah.com with alternative names: devops.blahblah.com
 + Creating new directory /etc/dehydrated/certs/devops_blahblah_com ...
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting new certificate order from CA...
 + Received 2 authorizations URLs from the CA
 + Handling authorization for devops.blahblah.com
 + Handling authorization for devops.blahblah.com
 + 2 pending challenge(s)
 + Deploying challenge tokens...
 + Godaddy hook executing: deploy_challenge
 + Updating TXT record for _acme-challenge.devops.blahblah.com to 'ngK9Tjbw7ZByLyiQNDUVRbQq2lLpDYlgVKtCvYp-EIE'.
 + Godaddy hook executing: deploy_challenge
 + Updating TXT record for _acme-challenge.blahblah.com to 'u2ikexgud3K1FwEdzIlFexJ6jCcWBBqBQ8bG4BNQBSw'.
 + Responding to challenge for devops.blahblah.com authorization...
 + Godaddy hook executing: invalid_challenge
 + invalid challenge for domain devops.blahblah.com: {
  "type": "dns-01",
  "status": "invalid",
  "error": {
    "type": "urn:ietf:params:acme:error:unauthorized",
    "detail": "Incorrect TXT record \"u2ikexgud3K1FwEdzIlFexJ6jCcWBBqBQ8bG4BNQBSw\" found at _acme-challenge.devops.blahblah.com",
    "status": 403
  },
  "url": "https://acme-v02.api.letsencrypt.org/acme/challenge/v0mLhPO8IXvvI81cfghcbvYEjrhBr8VJAx-sqik5v_U/4750319446",
  "token": "IjysecxQRpN0NytBmhbkLglFJ7InGLUyoGZwWJOwPI0"
}
 + Cleaning challenge tokens...
 + Godaddy hook executing: clean_challenge
...
 + Challenge validation has failed :(

```

Pretty consistent while everything else works, but wildcard certs don't.

**Comment by josteink** [comment]
Yeah that sounds about right. When I made this thing, ACMEv2 (and thus wildcard certs) where not a thing.

Lately though, someone by the handle of @javascriptdude [forked this repo](https://github.com/JavaScriptDude/le-godaddy-dns), and supposedly implemented support for wildcard certs (among other personal changes).

I asked him about it and he said he was going to issue some PRs back upstream to provide that kind of stuff in the mainline code, but  so far I haven't heard anything more.

If you need support for wildcard certs, I suspect the fastest and easiest way to get there is to inspect his work, what changes he has done to enable that, and issue a PR back here.

Do we have a deal? 😄

**Comment by JavaScriptDude** [comment]
Yep, my fork works with wildcards and has some other features. PR will be forthcoming. - Tim                                                                                                                                                                         Sent via the BlackBerry Hub for Android                                                                                                                                                                           From: notifications@github.comSent: May 22, 2018 4:06 AMTo: le-godaddy-dns@noreply.github.comReply to: reply@reply.github.comCc: tim.c.quinn@gmail.com; mention@noreply.github.comSubject: Re: [josteink/le-godaddy-dns] Wildcard certificate issues (#18)  Yeah that sounds about right. When I made this thing, ACMEv2 (and thus wildcard certs) where not a thing.
Lately though, someone by the handle of @JavaScriptDude forked this repo, and supposedly implemented support for wildcard certs (among other personal changes).
I asked him about it and he said he was going to issue some PRs back upstream to provide that kind of stuff in the mainline code, but  so far I haven't heard anything more.
If you need support for wildcard certs, I suspect the fastest and easiest way to get there is to inspect his work, what changes he has done to enable that, and issue a PR back here.
Do we have a deal? 😄

**Comment by Fleckz** [comment]
Yep, same problem here, does two challenges for 1 cert with two domains like example.com *.example.com.
I run it 3 times in a row, as fast as I can, first two does two challenges, last one does only one and succeeds!
Tried to do 8 domains (by pairs, root and wildcard for each), it does 8 challanges (should be 4), and in the end I got rate-limited by LE :( :D

**Comment by JavaScriptDude** [comment]
Did you use the code at my master? I've run against giant certs for wildcards for 50 domains at a time. - Tim                                                                                                                                                                         Sent via the BlackBerry Hub for Android                                                                                                                                                                           From: notifications@github.comSent: May 23, 2018 3:57 AMTo: le-godaddy-dns@noreply.github.comReply to: reply@reply.github.comCc: tim.c.quinn@gmail.com; mention@noreply.github.comSubject: Re: [josteink/le-godaddy-dns] Wildcard certificate issues (#18)  Yep, same problem here, does two challenges for 1 cert with two domains like example.com *.example.com.
I run it 3 times in a row, as fast as I can, first two does two challenges, last one does only one and succeeds!
Tried to do 8 domains (by pairs, root and wildcard for each), it does 8 challanges (should be 4), and in the end I got rate-limited by LE :( :D

**Comment by Fleckz** [comment]
Yep, maybe I am doing something wrong ?
how do you define domainA.com *.domainA.com domainB.com *.domainB.com domainC.com *.domainC.com in your domains.txt ? I did it like this... and I get two challenges for one domain... I repeat command until I get only one challenge and then it succeeds!

**Comment by JavaScriptDude** [comment]
Try setting this in your dehydrated config file:# Use GoDaddy Patch APY (set to yes for wildcards) (yes/no) gdpy_use_patch_api=yes # Enable Hook chain HOOK_CHAIN="yes"- Tim                                                                                                                                                                         Sent via the BlackBerry Hub for Android                                                                                                                                                                           From: notifications@github.comSent: May 23, 2018 9:00 AMTo: le-godaddy-dns@noreply.github.comReply to: reply@reply.github.comCc: tim.c.quinn@gmail.com; mention@noreply.github.comSubject: Re: [josteink/le-godaddy-dns] Wildcard certificate issues (#18)  Yep, maybe I am doing something wrong ?
how do you define domainA.com *.domainA.com domainB.com *.domainB.com domainC.com *.domainC.com in your domains.txt ? I did it like this... and I get two challenges for one domain... I repeat command until I get only one challenge and then it succeeds!

**Comment by josteink** [comment]
@JavaScriptDude: So if I understand your changes directly, what you've done to "fix" wildcard-support is using another way of adding the DNS-records via godaddypi.

I've implemented that [here](https://github.com/josteink/le-godaddy-dns/commit/b2ff2eb47a689b8ae9ff5b767a7df06f29cd5e08) in the [wildcard-branch](https://github.com/josteink/le-godaddy-dns/tree/wildcard).

What I've seen you do in your version though, is that you've also created a config-flag to toggle when to use this new updating-method.

That leaves me with a few questions:

* Are there any reasons you know about why this updated method shouldn't always be used?
* Are there any particular use-cases you know will fail using this technique?
* Do you foresee any problems with the changes as I've implemented them?

Cheers.

@Fleckz & @vogelfreiheit: Feel free to try my changes in your setup too, and let me know if you encounter any issues.

**Comment by JavaScriptDude** [comment]
Using the alternative api in godaddy always adds new records instead of updating existing. My concern with using add api by default is that it will continue to add new dns records when run multiple times.  Maybe it's not a big issue. I was dealing with hundreds of domains so was worried about the manual cleaning exercises. It's possible that I'm just being overly cautious :)- Tim                                                                                                                                                                           From: notifications@github.comSent: May 24, 2018 2:10 AMTo: le-godaddy-dns@noreply.github.comReply to: reply@reply.github.comCc: tim.c.quinn@gmail.com; mention@noreply.github.comSubject: Re: [josteink/le-godaddy-dns] Wildcard certificate issues (#18)  @JavaScriptDude: So if I understand your changes directly, what you've done to "fix" wildcard-support is using another way of adding the DNS-records via godaddypi.
I've implemented that here in the wildcard-branch.
What I've seen you do in your version though, is that you've also created a config-flag to toggle when to use this new updating-method.
That leaves me with a few questions:
Are there any reasons you know about why this updated method shouldn't always be used?Are there any particular use-cases you know will fail using this technique?Do you foresee any problems with the changes as I've implemented them?
Cheers.
@Fleckz & @vogelfreiheit: Feel free to try my changes in your setup too, and let me know if you encounter any issues.

**Comment by josteink** [comment]
Thanks for the feedback! I've verified, that yes, we're getting lots of duplicates.

I dislike having to choose between creating duplicates or not, so I've made the following change to master: https://github.com/josteink/le-godaddy-dns/commit/71ef1c95e63d9d1a4b656e8c77e4fa4d25d54980

We should now:

* first check if there are existing records.
* IF there are existing records, update them in place.
* IF there are not, add them (using patch API).

This should mimic your changes, @JavaScriptDude, but without the need for config-options. What do you think?

I've tested and been able to generate a wildcard cert for a subdomain, but I don't have any "main" domains I can test against now, because they're all already authorized.

@Fleckz & @vogelfreiheit: Can you check if the code in `master` works for you now?

**Comment by Fleckz** [comment]
Thanks for all your work! Sadly, I can't, I don't have any domains, I would have to revoke existing ones then.

**Comment by josteink** [comment]
No problem. Hope it all works out!

**Please note: I’ve now migrated my last domain *away* from godaddy, so I won’t personally be able to test or maintain this module, nor will I have a personal interest in doing so.**

Anyone willing to step up as a new maintainer is welcome to do so. I can either add you here, or you may just fork. 

I’ll get the readme updated and create a issue for this later if it is deemed necessary.

Cheers!

**Comment by JavaScriptDude** [comment]
I have many domains available for testing and will do so tonight. I will likely have testable domains for some time to come and don't mind becoming principal maintainer. -Tim                                                                                                                                                                         Sent via the BlackBerry Hub for Android                                                                                                                                                                           From: notifications@github.comSent: May 25, 2018 10:54 AMTo: le-godaddy-dns@noreply.github.comReply to: reply@reply.github.comCc: tim.c.quinn@gmail.com; mention@noreply.github.comSubject: Re: [josteink/le-godaddy-dns] Wildcard certificate issues (#18)  No problem. Hope it all works out!
Please note: I’ve now migrated my last domain away from godaddy, so I won’t personally be able to test or maintain this module, nor will I have a personal interest in doing so.
Anyone willing to step up as a new maintainer is welcome to do so. I can either add you here, or you may just fork.
I’ll get the readme updated and create a issue for this later if it is deemed necessary.
Cheers!

**Comment by Fleckz** [comment]
That's awesome! Thank you!

**Comment by JavaScriptDude** [comment]
Confirmed that issues exists. There is another issue that has arisen due to go-daddy api handling of "nulling" the challenge keys. I will raise and fix in another ticket.

**Comment by josteink** [comment]
Good research. 

But doesn’t that only apply when you have HOOK_CHAIN on?

I don’t use it because I don’t have so many domains, so that might be why testing worked for me. 

If so, that could be the “magic” switch which determines strategy?

**Comment by JavaScriptDude** [comment]
I will test with Hook chain off.                                                                                                                                                                          From: notifications@github.comSent: May 27, 2018 3:48 AMTo: le-godaddy-dns@noreply.github.comReply to: reply@reply.github.comCc: tim.c.quinn@gmail.com; mention@noreply.github.comSubject: Re: [josteink/le-godaddy-dns] Wildcard certificate issues (#18)  Good research.
But doesn’t that only apply when you have HOOK_CHAIN on?
I don’t use it because I don’t have so many domains, so that might be why testing worked for me.
If so, that could be the “magic” switch which determines strategy?

**Comment by JavaScriptDude** [comment]
Test is complete and the issue is still there. The foundation of dehydrated still follows the same flow which is (1) Load all challenges then (2) Verify each challenge.

**Comment by josteink** [comment]
Ok. Thanks for checking. 

I guess that means your original assumption holds, and we now know how to make the fix.

**Comment by JavaScriptDude** [comment]
I have branch [Wildcard_v2](https://github.com/josteink/le-godaddy-dns/tree/wildcard_v2) created. I've tested this and verified it works for my test cases.

**Comment by JavaScriptDude** [comment]
New code was released today to address the wildcard support. Essentially, its required to use HOOK_CHAIN="yes" setting in Dehydrated configuration file to support wildcard SAN certificate validation. See [README.md](https://github.com/josteink/le-godaddy-dns/blob/master/README.md) for details.

If anyone has issues with Wildcard certificates, please let us know.

**Comment by Fleckz** [comment]
Thank you, updated to new verison, worked great for 6 domains I have on first try! :)
